### CREATE USER

POST http://localhost:4001/users
Content-Type: application/json

{
    "name": "Favour Andabwa",
    "email": "favour2@gmail.com",
    "phone_no": "07046658508",
    "password": "123456"
    
}

###GET ALL USERS
GET http://localhost:4001/users
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgxMzJiMDg2LTkxNTktNGI2Ni1hY2IwLWYxYmQ4ZjkxNDFiYiIsImVtYWlsIjoiZmF2b3VyZ2FpdGFub0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcwOTA5MDI4NSwiZXhwIjoxNzA5MzQ5NDg1fQ.GGqPWzjFKi4toUTwgQncA_RCk9oNs2Zwjyhx1CcGbwU

###GET USER BY ID
GET http://localhost:4001/users/8132b086-9159-4b66-acb0-f1bd8f9141bb
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgxMzJiMDg2LTkxNTktNGI2Ni1hY2IwLWYxYmQ4ZjkxNDFiYiIsImVtYWlsIjoiZmF2b3VyZ2FpdGFub0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcwOTA5MDI4NSwiZXhwIjoxNzA5MzQ5NDg1fQ.GGqPWzjFKi4toUTwgQncA_RCk9oNs2Zwjyhx1CcGbwU

###UPDATE USER
PUT http://localhost:4001/users/8132b086-9159-4b66-acb0-f1bd8f9141bb
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgxMzJiMDg2LTkxNTktNGI2Ni1hY2IwLWYxYmQ4ZjkxNDFiYiIsImVtYWlsIjoiZmF2b3VyZ2FpdGFub0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcwOTA5MDI4NSwiZXhwIjoxNzA5MzQ5NDg1fQ.GGqPWzjFKi4toUTwgQncA_RCk9oNs2Zwjyhx1CcGbwU

{
    "name": "Favour Buyanzi",
    "email": "favourgaitano@gmail.com",
    "phone_no": "0722559750",
    "password": "123456"
    
}


###DELETE USER
DELETE http://localhost:4001/users/8132b086-9159-4b66-acb0-f1bd8f9141bb
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgxMzJiMDg2LTkxNTktNGI2Ni1hY2IwLWYxYmQ4ZjkxNDFiYiIsImVtYWlsIjoiZmF2b3VyZ2FpdGFub0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcwOTA5MDI4NSwiZXhwIjoxNzA5MzQ5NDg1fQ.GGqPWzjFKi4toUTwgQncA_RCk9oNs2Zwjyhx1CcGbwU


